### ISSUE TITLE
uninitalize constant in schedule tab

### ISSUE THREAD

**Issue by andreacfm** [resque/resque-scheduler#110]
Test case:

Schedule

```
breakfast:
  every: 5s
  class: Eat
  args: scrambled egg
  description: Breakfast
```

Class Eat exists and schedule runs fine but when I try to see the schedule tab I get error:

```
uninitialized constant Eat
file: helpers.rb location: const_get line: 58
```

V 1.9.9

Andrea
