### ISSUE TITLE
Schedule doesn't work, "Internal Server Error" on "Queue now"

### ISSUE THREAD

**Issue by manuelmeurer** [resque/resque-scheduler#139]
I added resque-scheduler to my project but it doesn't seem to work.
I'm using Ruby 1.9.3, Rails 3.2.2 and Resque 1.20.0.

My `config/resque_schedule.yml`:

```
send_daily_summary:
  cron: 0 1 * * *
  queue: cron
  class: ResqueScheduleTask
  args: send_daily_summary
  description: Send daily summary
  rails_envs: production
```

The task shows up in Resque-Web (http://screencast.com/t/vVOiwUQ4cCwD) but it is never executed, and when I click "Queue now" I get a "Internal Server Error". Nothing is written to any log file though, so I can't see what's wrong.
When I execute `ResqueScheduleTask.perform(:send_daily_summary)` manually, it works just fine.
