### ISSUE TITLE
Resque::NoQueueError: Jobs must be placed onto a queue.

### ISSUE THREAD

**Issue by softwaregravy** [resque/resque-scheduler#169]
Anyone get this occasionally?

For us, we started to see this a week or so ago. It crops every couple of days, and then just keeps happening. We fix it by restarting the scheduler process. We're running on Heroku using RedisToGo (resque is basically our only use of Redis). The error is not very illuminating.

``` logs
2012-07-14T04:09:00+00:00 app[scheduler.1]: 2012-07-14 04:09:00 queueing VeniceHeartbeat (heartbeat_to_venice)
2012-07-14T04:09:00+00:00 app[scheduler.1]: 2012-07-14 04:09:00 Resque::NoQueueError: Jobs must be placed onto a queue.
```

This job runs all the time, and works well over 99% of the time. Occasionally, though, it just stops working. We have not yet verified if other scheduled jobs also fail to be scheduled.

The config entry for this:

``` yaml
heartbeat_to_venice:                                                                                                                                                                                                                                                          
  cron: "* * * * *"
  class: VeniceHeartbeat
  args:
  description: "Lets venice know we're alive"
```

Worth noting, the job absolutely specifies the `@queue` member, and this job works pretty much all the time. 

Here's some stuff out of our Gemfile.lock:

``` gemfile
GIT
  remote: git://github.com/bvandenbos/resque-scheduler
  revision: 9db9e9e2512636d31d9d9f8e0a761b74f3f43408
  specs:
    resque-scheduler (2.0.0.h)                                                                                                                                                                                                                                                
      redis (>= 2.0.1)         
      resque (>= 1.20.0)       
      rufus-scheduler          

   resque (1.20.0)         
```
