### ISSUE TITLE
Multiple occurrences of the same job class 

### ISSUE THREAD

**Issue by mdi** [resque/resque-scheduler#184]
For example, I have these jobs defined in my schedule:

```
oh_my_rockness_chicago:
  cron: '0 12 * * * Etc/UTC'
  class: OhMyRockness
  args: http://chicago.ohmyrockness.com/
oh_my_rockness_los_angeles:
  cron: '0 12 * * * Etc/UTC'
  class: OhMyRockness
  args: http://losangeles.ohmyrockness.com/
oh_my_rockness_new_york:
  cron: '0 12 * * * Etc/UTC'
  class: OhMyRockness
  args: http://www.ohmyrockness.com/
```

Only the first one is queued, and the others give an error like:

```
LoadError: Expected oh_my_rockness.rb to define OhMyRockness
```

So the others aren't queued. Is this a bug or am I doing something wrong?
