### ISSUE TITLE
Issue using every without array args

### ISSUE THREAD

**Issue by Floppy** [resque/resque-scheduler#338]
I've just upgraded to 2.4, and the code we used to have in schedule.yml no longer works. The only change in the update was the resque-scheduler version. See https://github.com/theodi/services-manager/commit/827d549d6dafb2f83c4a0b9586761ccc7da9761f for proof.

We had:

```
dashboard_time:
  every: 1m
  class: DashboardTime
  args: 
  description: "Updates the time on the dashboard every 1 minute"
```

But now, this raises the error:

```
NoMethodError at /schedule
undefined method `map' for "m":String
file: server.rb location: schedule_interval_every line: 40
```

If, instead, we change to the array args syntax:

```
dashboard_time:
  every: 
    - 1m
  class: DashboardTime
  args: 
  description: "Updates the time on the dashboard every 1 minute"
```

everything works.

Is this expected? The README should be updated if it is...
