### ISSUE TITLE
Get time of scheduled job

### ISSUE THREAD

**Issue by chenkirk** [resque/resque-scheduler#380]
Is there a way to get the time a job was scheduled in the job? If not is it something that can be added easily (please point me in the right direction).

For example, I have my resque_scheduler set run clean up task every 2 min. The clean up task will clean up items in the 2 min interval. This is my yml:

``` yaml
scheduled_tasks:
  cleanup:
    class: "BackgroundJobs::Cleanup"
    every: "120s"
    description: "cleans up items in the 2 min interval"
```

Here's the job

``` ruby
module BackgroundJobs
  class Cleanup
    @queue = :cleanup

    def self.perform(options = {})
      # do cleanup here
    end
  end
end
```

The job queues fine and is picked up fine. However, in the perform, it needs to know what period it's supposed to cleanup. For exampled, if something is queued at 2:32, I want it to clean up items from 2:30 to 2:32. However, the job might not be picked up until much later, e.g. 2:35. I have no information about when it was queued.
