### ISSUE TITLE
**every** jobs have inconsistent enqueueing schedule

### ISSUE THREAD

**Issue by ce-manalang** [resque/resque-scheduler#388]
Hi guys,

My scheduler setup is

```
job_1:
  every: 5s

job_2:
  cron: '*/1 * * * *'
```

When I look at the scheduler log, I noticed that the cron job is queued exactly every minute but the **every** job isn't queued exactly every 5 seconds.

Anyone here encountered this? Maybe you guys can enlighten me.

Thanks!
