### ISSUE TITLE
It's not clear how EVERY works..

### ISSUE THREAD

**Issue by dyatlov** [resque/resque-scheduler#462]
for example I have this in `resque_schedule.yml`:

```
send_notifications:
  every:
    - "10s"
  class: "NotificationsSender"
```

What if job lasts `20s`?
Will it wait for it to complete or it will start the same process again while previous still running?

If I have another job in addition to the above which runs every 15 seconds.. will the above affect that run?
Or second job would run normally?
