### ISSUE TITLE
How to stop / start one scheduler?

### ISSUE THREAD

**Issue by weilluo** [resque/resque-scheduler#497]
resque_schedule.yml
```yaml
batch_watch_dog:
  cron: "*/5 * * * *"
  class: "Job::WatchDog"
  args:
    times: 30

sync_up_migration:
  cron: "30 1 * * *"
  class: "Job::SyncUpConfigs"
```

config/initializers/resque.rb
```ruby
Resque::Scheduler.dynamic = true
if Resque.schedule.nil? || Resque.schedule.empty?
  Resque.schedule = YAML.load_file(Rails.root.join('config', 'resque_schedule.yml'))
end
```

After I start the schedule, I can edit the `cron` runtime, when I restart the schedule I can also use the edited `cron`.

But when I want to stop a schedule, for example `sync_up_migration`, in my current solution, I give a invalid `cron`, like `##30 1 * * *`.

So, I want to know my solution is correct? and Is there some other more appropriate solution? @yaauie
