### ISSUE TITLE
Strange error and behaviour on the web interface

### ISSUE THREAD

**Issue by ciaoben** [resque/resque-scheduler#544]
Here is my initializer:

`resque-init.rb`
```
# This will make the tabs show up.
require 'resque'
require 'resque-scheduler'
require 'resque/scheduler/server'

Resque.redis = Redis.new(:host => 'localhost', :port => 6379)
Resque.schedule = YAML.load_file('./config/resque_schedule.yml')
```

With this, and empty redis everything work, I lunch:

```
rake resque:scheduler
 resque-web ./resque-init.rb
```

and I see the interface and the one scheduled job of my `./config/resque_schedule.yml`:
```
queue_documents_for_indexing:
  cron: "*/2 * * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1h
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  args: 
    - "create"
    - "12324"
  class: "DomainsJobs"
  queue: :file_serve
```

But if I create a new dynamic schedule:

```
    name = 'delete_domain'
    config = {}
    config[:class] = 'DomainsJobs'
    config[:args] = 'create'
    config[:cron] = "*/2 * * * *"
    config[:persist] = true
    Resque.set_schedule(name, config)
```

In redis it shows up under the key `resque:persistent_schedules`.
If I refresh the interface I can't see it. And if I stop the interface and restart it, I get the sinatra error page with:
![schermata 2016-05-16 alle 15 36 23](https://cloud.githubusercontent.com/assets/4526061/15290965/00a46166-1b7c-11e6-9226-2d830f66b8a4.png)

Here is the backtrace:

![schermata 2016-05-16 alle 15 37 28](https://cloud.githubusercontent.com/assets/4526061/15290996/25371730-1b7c-11e6-99a3-7573d0f0dd35.png)

What can be the problem? What am I missing?
