### ISSUE TITLE
Cron 5* syntax not working

### ISSUE THREAD

**Issue by slucha** [resque/resque-scheduler#606]
I have a standard static job schedule which works if I set it to run every hour on the 15th minute and 45 second  with a 6* cron syntax

```
tweet_sender:
  cron: "45 15 * * * *"
  class: "TweetSender"
  queue: tweets_queue
  args: tweet_id
  rails_env: development
  description: "This job sends daily tweets from the content db"
```

If I change it to a regular 5* cron syntax to rum for example once per day at 2:10   cron: "10 2 * * * " the jobs do not get schedueled
