### ISSUE TITLE
Examples for args?

### ISSUE THREAD

**Issue by zachwalton** [resque/resque-scheduler#615]
I defined this:

```
recurring_task:
  every:
    - "10s"
    - :first_in: "1m"
  class: ScheduledTask
  args:
    staleness_threshold_minutes: 180
    stale: no
```

...and was a bit surprised that the args passed to `ScheduledTask.perform` were:

```
  [
    u'staleness_threshold_minutes', 
    180
  ], 
  [
    u'stale', 
    False
  ]
```

Would it be possible to add some examples of using args in `examples/`? Are kwargs not supported?
