### ISSUE TITLE
Prevent scheduled job from being enqueued if another instance is already enqueued

### ISSUE THREAD

**Issue by danielbonnell** [resque/resque-scheduler#622]
This is more of a question than an issue report. I have the following in my `resque_schedule.yml`

```
update_contact_ranks:
   every: 1m
   class: UpdateContactRanks
   args:
   description: Updates all contact ranks

```

Simply put, I would like to know if there is a built-in way that I can tell the scheduler not to enqueue `UpdateContactRanks` if it's already in the queue. For example, if all my workers are busy performing other jobs and five minutes elapse, the job would be added to the queue five time and be processed five consecutive times, which adds no value and ties up workers that could be doing other jobs.

If there is a way to specify a queue's priority in the yml file, that would get at my problem as well (since this job only takes about 4 seconds to process), however I would still like to know if deduplication like this is possible.
