### ISSUE TITLE
resque-scheduler (4.3.1) bug with rufus-scheduler (3.5.0)

### ISSUE THREAD

**Issue by Nkadze** [resque/resque-scheduler#649]
Hi,
This happens when it tries to start schedule from scheduler file, 
```
NoMethodError: undefined method `next_time' for nil:NilClass
/app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler/jobs.rb:640:in `next_time_from'
```
cron type:
```
my_job_name:
  cron:  '/15 * * * *' # every 15 minutes
  queue: queue_name
  class: ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
  args:
    job_class: JobClassName
    queue_name: queue_name
  description: "This job runs every 15 minutes"
```

when I locked `rufus-scheduler '~> 3.4.2' ` in gemfile, it was solved

Thanks,
Niko
