### ISSUE TITLE
Web UI should only show jobs loaded in that environment

### ISSUE THREAD

**Issue by calebperkins** [resque/resque-scheduler#86]
I have the following job specified in my resque_schedule.yml file. It is meant only for production mode, but it still appears on the Schedule tab in the web interface in development mode.

``` yml
sync_s3:
  cron: "00 0 * * *"
  class: Product
  rails_env: production
  description: "Sync product images with Amazon S3 every day at midnight PT"
```
